[硬改内存切换]

[4G内存模式]
try:
  cp ./Data/payload.bin.4g /payload.bin
  set-ini-val /exosphere.ini exosphere enable_mem_mode 0
  del ./config.ini
  set-footer "已启用"

[8G内存模式 - 非硬改8G勿动]
try:
  cp ./Data/payload.bin.8g /payload.bin
  set-ini-val /exosphere.ini exosphere enable_mem_mode 1
  del ./config.ini
  set-footer "已启用"

[重启生效]
[立即重启]
reboot

[提示]
[$]
;mode=table
;spacing=1
;gap=0

'此选项为内存硬件改动的玩家提供'=''
' '=''
'非8G内存硬件的玩家请勿修改此项'=''
''=''





