[DBI语言设置]
[*语言选择]
;mode=option
json_file_source './Data/DBI.json' name
unzip  {json_file_source(*,path)} /
set-footer '{json_file_source(*,label)}'

[提示]
[$]
;mode=table
;spacing=1
;gap=0
' 快速切换语言版本'=''
''=''
' 用来解决老版本可能产生的问题'=''
