;creator=gzk_47
;version=v1.0.0
;about='启用/禁用 插件'
[请勿禁用 ovlmenu.ovl]
[*切换插件]
;mode=toggle
filter /switch/.overlays/ovlmenu.ovl
on:
    file_source /switch/.overlays/*.ovl
    mkdir /switch/.overlays/.offload/
    move {file_source} /switch/.overlays/.offload/
off:
    file_source /switch/.overlays/.offload/*.ovl
    move {file_source} /switch/.overlays/
[请勿禁用 XY-tools]
[*切换软件包]
;mode=toggle
filter /switch/.packages/XY-tools/Broomstick/
on:
    filter /switch/.packages/.offload/
    file_source /switch/.packages/*/
    mkdir /switch/.packages/.offload/
    move {file_source} /switch/.packages/.offload/{file_name}/
off:
    file_source /switch/.packages/.offload/*/
    move {file_source} /switch/.packages/{file_name}/
[默认不禁用 ovlmenu.ovl]
[启用所有插件]
move /switch/.overlays/.offload/EdiZon.ovl /switch/.overlays/
move /switch/.overlays/.offload/QuickNTP.ovl /switch/.overlays/
move /switch/.overlays/.offload/emuiibo.ovl /switch/.overlays/
move /switch/.overlays/.offload/FPSLocker.ovl /switch/.overlays/
move /switch/.overlays/.offload/ldn_mitm.ovl /switch/.overlays/
move /switch/.overlays/.offload/ovlEdiZon.ovl /switch/.overlays/
;move /switch/.overlays/.offload/ovlmenu.ovl /switch/.overlays/
move /switch/.overlays/.offload/ovl-sysmodules.ovl /switch/.overlays/
move /switch/.overlays/.offload/QuickNTP.ovl /switch/.overlays/
move /switch/.overlays/.offload/ReverseNX-RT.ovl /switch/.overlays/
move /switch/.overlays/.offload/StatusMonitor.ovl /switch/.overlays/
move /switch/.overlays/.offload/sys-clk.ovl /switch/.overlays/
move /switch/.overlays/.offload/SysDVR.ovl /switch/.overlays/
move /switch/.overlays/.offload/sys-patch-overlay.ovl /switch/.overlays/
[默认不禁用 ovlmenu.ovl]
[禁用所有插件]
mkdir /switch/.overlays/.offload/
move /switch/.overlays/EdiZon.ovl /switch/.overlays/.offload/
move /switch/.overlays/emuiibo.ovl /switch/.overlays/.offload/
move /switch/.overlays/FPSLocker.ovl /switch/.overlays/.offload/
move /switch/.overlays/ldn_mitm.ovl /switch/.overlays/.offload/
move /switch/.overlays/ovlEdiZon.ovl /switch/.overlays/.offload/
;move /switch/.overlays/ovlmenu.ovl /switch/.overlays/.offload/
move /switch/.overlays/ovl-sysmodules.ovl /switch/.overlays/.offload/
move /switch/.overlays/QuickNTP.ovl /switch/.overlays/.offload/
move /switch/.overlays/ReverseNX-RT.ovl /switch/.overlays/.offload/
move /switch/.overlays/StatusMonitor.ovl /switch/.overlays/.offload/
move /switch/.overlays/sys-clk.ovl /switch/.overlays/.offload/
move /switch/.overlays/SysDVR.ovl /switch/.overlays/.offload/
move /switch/.overlays/sys-patch-overlay.ovl /switch/.overlays/.offload/

[Package Info]
