
[屏蔽任天堂服务器]
[虚拟系统 联网屏蔽]
;mode=toggle
on:
cp './Data/emummc.txt' /atmosphere/hosts/

off:
del '/atmosphere/hosts/emummc.txt'

[真实系统 联网屏蔽]
;mode=toggle
on:
cp './Data/sysmmc.txt' /atmosphere/hosts/

off:
del '/atmosphere/hosts/sysmmc.txt'



[屏蔽机身序列号]
[真实系统 序列号屏蔽]
;mode=toggle
on:
cp './Data/exosphere1.ini' /exosphere.ini

off:
cp './Data/exosphere0.ini' /exosphere.ini

[提示]
[$]
;mode=table
;spacing=1
;gap=0

' 虚拟系统和真实系统默认都屏蔽机身序列号。'=''
''=''
' 请勿随便关闭屏蔽保护，以免Ban机！'=''
''=''
