
[屏蔽任天堂服务器]
[真实系统 服务器屏蔽]
;mode=toggle
on:
cp './Data/sysmmc.txt' /atmosphere/hosts/
off:
del '/atmosphere/hosts/sysmmc.txt'


[屏蔽机身序列号]
[真实系统 序列号屏蔽]
;mode=toggle
on:
set-ini-val /exosphere.ini exosphere blank_prodinfo_sysmmc 1
off:
set-ini-val /exosphere.ini exosphere blank_prodinfo_sysmmc 0

[取消系统破解]
[真实系统 破解补丁]
;mode=toggle
on:
set-ini-val /config/sys-patch/config.ini options patch_sysmmc 1
off:
set-ini-val /config/sys-patch/config.ini options patch_sysmmc 0

[重启生效]
[立即重启]
reboot

[提示]
[$]
;mode=table
;spacing=1
;gap=0

' 如需联网，建议取消真实系统破解 '=''
' '=''
' 虚拟和真实系统默认都屏蔽服务器和机身序列号。'=''
' '=''
' 请勿随便关闭屏蔽保护，以免Ban机！'=''
' '=''
